version: "3.1"
services:
  web_ui:
    container_name: ydl_web_ui
    image: nxhs/ydl-web-ui
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - 4011:3000
    environment:
      - YDL_API_HOST=http://api:80
    networks:
      - ydl_api_ng

  api:
    container_name: ydl_api_ng
    image: totonyus/ydl_api_ng
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - 5011:80
    volumes:
      - ./params:/app/params
      - ./logs:/app/logs
      - ./downloads:/app/downloads
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - UID=1000
      - GID=1000
      - NB_WORKERS=5
      - LOG_LEVEL=error
      # Redis will be disable is this value is not false, remember to also change the setting in params.ini file
      - DISABLE_REDIS=false
    networks:
      - ydl_api_ng

  redis:
    container_name: ydl_api_ng_redis
    image: redis
    restart: unless-stopped
    networks:
      - ydl_api_ng
    volumes:
      - /etc/localtime:/etc/localtime:ro

networks:
  ydl_api_ng:
